---
apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: mysql-rds-app
spec:
  application: rds-app
  cloudResource:
    plan: appvia-rds-mysql
    planVersion: 1.0.0
    variables:
      # db_name below will be prefixed with the app environment name
      # when component gets deployed as database names must be unique
      # within the same AWS account. See the referencced CR plan for more info.
      db_name: todos
      allocated_storage: 10
      instance_class: db.t3.micro
  key: mysql
  name: mysql-rds-app
  type: CloudResource
---
apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: app-rds-app
spec:
  application: rds-app
  container:
    containers:
      - env:
          - name: MYSQL_HOST
            fromCloudResourceOutput:
              componentName: mysql-rds-app
              output: DATABASE_HOST
          - name: MYSQL_USER
            fromCloudResourceOutput:
              componentName: mysql-rds-app
              output: DATABASE_USER
          - name: MYSQL_PASSWORD
            fromCloudResourceOutput:
              componentName: mysql-rds-app
              output: DATABASE_PASSWORD
          - name: MYSQL_DB
            fromCloudResourceOutput:
              componentName: mysql-rds-app
              output: DATABASE_NAME
        image: trialm6kl97.jfrog.io/docker-trial/rds-app:latest
        name: app
        ports:
          - containerPort: 3000
            expose: true
            name: http
            protocol: TCP
    expose:
      container: app
      port: 3000
    replicas: 1
    tls: true
  key: app
  name: app-rds-app
  type: Container
